<?php if ($this->pageCount): ?>
    <div class="row">
        <ul class="pagination pagination-centered">
            <!-- Records Info -->
            <li>
             <span><?php echo $this->firstItemNumber; ?> - <?php echo $this->lastItemNumber; ?>
            of <?php echo $this->totalItemCount; ?>
                 </span>
            </li>
            <!-- First page link -->
            <?php if (isset($this->previous)): ?>
                <li>
                    <a href="<?php echo $this->url($this->route, array('id' => $this->first)); ?>">
                        |<
                    </a>
                </li>
            <?php else: ?>
                <li class="disabled">
                    <a href="#">
                        |<
                    </a>
                </li>
            <?php endif; ?>
            <!-- Previous page link -->
            <?php if (isset($this->previous)): ?>
                <li>
                    <a href="<?php echo $this->url($this->route, array('id'=>$this->previous)); ?>">
                        <<
                    </a>
                </li>
            <?php else: ?>
                <li class="disabled">
                    <a href="#">
                        <<
                    </a>
                </li>
            <?php endif; ?>
            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?>
                <?php if ($page != $this->current): ?>
                    <li>
                        <a href="<?php echo $this->url($this->route,  array('id'=>$page)); ?>">
                            <?php echo $page; ?>
                        </a>
                    </li>
                <?php else: ?>
                    <li class="active">
                        <a href="#"><?php echo $page; ?></a>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>

            <!-- Next page link -->
            <?php if (isset($this->next)): ?>
                <li>
                    <a href="<?php echo $this->url($this->route,  array('id'=>$this->next)); ?>">
                        >>
                    </a>
                </li>
            <?php else: ?>
                <li class="disabled">
                    <a href="#">
                        >>
                    </a>
                </li>
            <?php endif; ?>

            <!-- Last page link -->
            <?php if (isset($this->next)): ?>
                <li>
                    <a href="<?php echo $this->url($this->route, array('id' => $this->last)); ?>">
                        >|
                    </a>
                </li>
            <?php else: ?>
                <li class="disabled">
                    <a href="#">
                        >|
                    </a>
                </li>
            <?php endif; ?>
        </ul>
    </div>
<?php endif; ?>