<nav class="navbar navbar-inverse navbar-fixed-top"  role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<?php echo $this->url('home') ?>">&nbsp;<?php echo $this->translate('Skeleton Application') ?></a>
            </div><!-- /.navbar-header -->
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <?php $count = 0; ?>
                    <?php foreach ($this->container as $page): ?>
                        <?php //var_dump($page); exit;?>
                        <?php /* @var $page Zend\Navigation\Page\Mvc */ ?>
                        <?php // when using partials we need to manually check for ACL conditions ?>
                        <?php if( ! $page->isVisible() || !$this->navigation()->accept($page)) continue; ?>
                        <?php $hasChildren = $page->hasPages() ?>
                        <?php if( ! $hasChildren): ?>
                            <li>
                                <a href="<?php echo $page->getHref() ?>">
                                    <?php echo $this->translate($page->getLabel()) ?>
                                </a>
                            </li>
                        <?php else: ?>
                            <li class="dropdown">
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                    <?php echo $this->translate($page->getLabel()) ?><b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu">
                                    <?php foreach($page->getPages() as $child): ?>
                                        <?php // when using partials we need to manually check for ACL conditions ?>
                                        <?php if( ! $child->isVisible() || !$this->navigation()->accept($child)) continue; ?>
                                        <li>
                                            <a href="<?php echo $child->getHref() ?>">
                                                <?php echo $this->translate($child->getLabel()) ?>
                                            </a>
                                        </li>
                                    <?php endforeach ?>
                                </ul>
                            </li>
                        <?php endif ?>
                        <?php $count++; ?>
                    <?php endforeach ?>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Guest <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="<?php echo $this->basePath('/accounts');?>">Account</a></li>
                            <li><a href="<?php echo $this->basePath('/accounts/privacy');?>">Privacy</a></li>
                            <li class="divider"></li>
                            <li><a href="<?php echo $this->basePath('/auth/logout');?>">Logout</a></li>
                        </ul>
                    </li>
                </ul>
            </div><!-- /.nav-collapse -->
    </div><!-- /.container -->
</nav><!-- /.navbar -->