<?php
/**
 *
 * User: winston.c
 * Date: 07/11/13
 * Time: 11:48 AM
 * 
 */


$title = 'Authenticate User';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();